language: python
cache: pip

python:
  - "3.5"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

before_deploy:
  - pyb -X package

deploy:
  provider: pypi
  user: esc
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "oADOP/f+Kysp8n2aAT7D2H1Pv6zjrUwB44gCRvnncOYeSG+F5Q03+NltiiRIbKDW6GAKnoNUisdf0u7GpEDFM4ive8voWtNM/Oe3XMhX8VN4UFl5a13VBVZZDZO6RvFL+p5sUiFLNWWbrvEhZgqgIa6y6hZXPvpxwl2rV1vMwygDUKd8fvH7AKaMXx8SZCFx16JwCSz1HYJ56ZpFOfFvPnDN1VShTZPJi1k4QesPM1IuE0Zd6oKTeiOemOKpNk9PY6xUG5GO6moobcGDQqcC9VauGwahK7D2EW5BZLJ00e6d5FgXi6/ywOmOmOrMeuKnQFLusYfc8ysYztHHsBpRLDaxvdmpMUQAAPgbRh2vz4NZuWR0aJB0qu7wKC4bkA9xtmeOWujiJC3O+btutLmv0xOcdCNfXgDUFvOt34Af8wnFENQT4D7RuBLre4gZAhqCVvlwOeStxKbcbbBGj0ZIo6cUPoNaD8Hd7T45UpebUEbUS8mrNgb73pN7v2bm5K2N7bQEFvsN5YaHAQNxYBAN5EKSDcNhXm4xWVifdcm41dCXseP1g3o5nE3P8U8uLd2znNdSGVDVgA81ZaNP5hEQsG57LpMDxIMk25V2mau5syjIs68uHavC2XSMjldgUtmfpXGEeiXpt/WizaAbKeYhrQwb8UPvGYWc1+7x82v+atU="
  on:
    repo: esc/yadoma
    python: '3.5'
    branch: master
